Algoritmo "Celsius"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   :  Jailson
// Descrição   : Solicita o grau dem fahrenheit e exibe o valor da conversão para celsius
// Autor(a)    : Alanis Ribeiro
// Data atual  : 16/03/2023

Var
// Seção de Declarações das variáveis 
celsius:real
fah:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("Digite o valor em grau fahrenheit:")
Leia (fah)
celsius<- (fah-32)*5/9
Escreva ("O valor em celsius é:",celsius,"º")


Fimalgoritmo