Algoritmo "antecessor"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   :  Solicita um número e exibe o antecessor
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
numero1:inteiro
antecessor:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("Digite um número")
Leia (numero1)
antecessor:=numero1-1
Escreva ("O antecessor do número é: ",antecessor)

Fimalgoritmo