Algoritmo "Salario vendedor"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   :  Jailson
// Descrição   : Solicita o numero de carros vendidos, total de vendas, salario fixo e a comissão do vendedor e exibe o salario final do vendedor.
// Autor(a)    : Alanis Ribeiro
// Data atual  : 16/03/2023
Var
// Seção de Declarações das variáveis 
carrosvendidos:real
vendas:real
salariofixo:real
comissao:real
comissaofixatotal:real
comissaovariavel:real
valortotal:real
total:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("Digite o número de carros vendidos;")
Leia (carrosvendidos)
Escreva ("Digite o total de vendas:")
Leia (vendas)
Escreva ("Digite o salário fixo do vendedor:")
Leia (salariofixo)
Escreva ("Digite o valor da comissão:")
Leia (comissao)
comissaofixatotal<-carrosvendidos*comissao
comissaovariavel<- 5/100*valortotal
total<-comissaofixatotal+comissaovariavel+salariofixo
Escreva ("O total é de: ", total)





Fimalgoritmo