Algoritmo "sucessor"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa
// Descrição   : Solicita um número e exibe o sucessor desse número
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
numero1:inteiro
sucessor:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreva ("Digite um número")
 Leia (numero1)
 sucessor:=numero1+1
 Escreva ("O sucessor do número é:", sucessor)

Fimalgoritmo