Algoritmo "circulo"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Solicita que o usuário digite o raio do circulo, faz a operação e exibe o valor da área do circulo)
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
raio:real
area:real




Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("Digite o raio do circulo:")
Leia (raio)
area<-PI*raio*raio
Escreva ("A área do circulo é: ", area)



Fimalgoritmo