Algoritmo "retângulo"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Solicita a altura e a base do retângulo e exibe a área do retângulo
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
altura:real
base:real
area:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("Digite a altura do retângulo:")
Leia (altura)
Escreva ("Digite a base do retângulo:")
Leia (base)
area<- altura*base
Escreva ("A área do retângulo é: ", area)




Fimalgoritmo