Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
altura:real
base:real
area:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("Digite a altura do triângulo:")
Leia(altura)
Escreva ("Digite a base do triângulo")
Leia(base)
area<- base*altura/2
Escreva ("A área do triângulo é: ", area)




Fimalgoritmo