Algoritmo "Salario"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/03/2023
Var
// Seção de Declarações das variáveis 
salario:real
percentual:real
salarionovo:real



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreva ("Digite o salário atual:")
Leia (salario)
Escreva ("Digite o percentual de reajuste:")
Leia (percentual)
salarionovo<-salario+(salario*percentual/100)
Escreva ("O valor do novo salário é de:", salarionovo)


Fimalgoritmo