Algoritmo "Ex J - Pag 66 Manzano"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   :    Elaborar um programa que apresente os valores de conversão de graus Celsius em Fahrenheit, de 10 em 10 graus, iniciando a contagem em 10 graus Celsius e finalizando em 100 graus Celsius. O programa   deve   apresentar   os   valores   das   duas   temperaturas.   A   fórmula   de   conversão é51609+=CF, sendo F a temperatura em Fahrenheit e C a temperatura em Celsius.
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
contador:inteiro
fahrenheit:real



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para contador de 10 ate 100 passo 10 faca
fahrenheit<-(9*contador+160)/5
escreval(fahrenheit)
contador<-contador+1
fimpara




Fimalgoritmo
