Algoritmo "Ex A - Pag 66 Manzano"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200.
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis
contador:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para contador de 15 ate 200 passo 1 faca
contador<-(contador*contador)
escreval(contador)
fimpara


Fimalgoritmo

