Algoritmo "Ex K - Pag 66 Manzano"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Elaborar  um  programa  que  apresente  como  resultado
//o  valor  do  fatorial  do  valor solicitado
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
   // Seção de Declarações das variáveis
numero:inteiro
contador:inteiro
fatorial:inteiro




Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
fatorial<-1
escreval("Digite um número e receba o valor do fatorial:")
leia(numero)
para contador de numero ate 1 passo -1 faca
fatorial<-fatorial*contador
fimpara
escreva(fatorial)
   



Fimalgoritmo

