Algoritmo "Ex B - Pag 66 Manzano"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresentar os resultados de uma tabuada de multiplicar (de 1 até 10) de um número qualquer.
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
contador:inteiro
numero:inteiro
multiplicacao:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
contador<-1
escreval("Digite um número e receba sua tabuada:")
leia(numero)
para contador de 1 ate 10 passo 1 faca
multiplicacao<-numero*contador
escreval(numero," x ",contador," = ", multiplicacao)
contador<-contador+1

fimpara
Fimalgoritmo
