Algoritmo "Ex C - Pag 66 Manzano"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   :  Apresentar o total da soma obtida dos cem primeiros números inteiros (1+2+3+4+...+98+99+100).
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
contador:inteiro
soma:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para contador de 1 ate 100 passo 1 faca
soma<-soma+contador
escreval(soma)
fimpara



Fimalgoritmo
