Algoritmo "Ex D - Pag 66 Manzano"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Elaborar um programa que apresente no final o somatório dos
//valores pares existentes na faixa de 1 até 500.
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/20233
Var
// Seção de Declarações das variáveis
contador:inteiro
soma:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para contador de 1 ate 500 passo 1 faca
se contador mod 2 = 0 entao
soma<-soma+contador
escreval(soma)
contador<-contador+1
fimse
fimpara




Fimalgoritmo
