Algoritmo "Ex F - Pag 66 Manzano"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresentar  todos  os  números  divisíveis  por  4  que  sejam  menores  que  200.  Para  verificar  se  o número  é  divisível  por  4,  efetuar  dentro  da  malha  a  verificação  lógica  desta  condição  com  a instrução se,  perguntando  se  o  número  é  divisível;  sendo,  mostre-o;  não  sendo,  passe  para  o próximo passo. A variável que controlará o contador deve ser iniciada com o valor 1.
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
contador:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
contador<-contador+1
para contador de 1 ate 200 passo 1 faca
se contador mod 4 = 0 entao
escreval(contador)
fimse
fimpara


Fimalgoritmo
