Algoritmo "L01M"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Faz o quadrado da soma dos 3 número solicitados
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
a:inteiro
b:inteiro
c:inteiro
resultado:inteiro
soma:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o 1º valor:")
leia(a)
escreva("Digite o 2º valor:")
leia(b)
escreva("Digite o 3º valor:")
leia(c)
soma<-a+b+c
resultado<-soma*soma
escreva ("O quadrado da soma desses 3 números é de:",resultado)



Fimalgoritmo