Algoritmo "L01J"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicita o valor em dolar e converte para real
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis
dolar:real
reais:real
cotacao:Real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Digite a atual cotação do dolar:")
leia(cotacao)
escreva ("Digite quantos doláres você tem:")
leia(dolar)
reais<-dolar*cotacao
Escreva ("O valor convertido para real é de:", reais, "R$")


Fimalgoritmo