Algoritmo "L01A"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   :  Solicita os graus em celsius e converte para fahrenheit
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
celsius:real
fahrenheit:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("Digite a temperatura em graus celsius")
Leia (celsius)
fahrenheit<-(9*celsius+160)/5
Escreval ("A temperatura em fahrenheit é de", fahrenheit,"º")



Fimalgoritmo