Algoritmo "L01K"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicita o valor em real e converte para dolar
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
dolar:real
reais:real
cotacao:real



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o valor da cotação do dolar:")
leia(cotacao)
escreval("Digite a quantidade de reais que você tem:")
leia(reais)
dolar<-reais/cotacao
escreva("O valor em dolar é de:", dolar,"$")


Fimalgoritmo