Algoritmo "L01L"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Faz o valor da soma do quadrado dos 3 valores solicitados
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis
a:inteiro
b:inteiro
c:inteiro
resultado:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o 1º valor:")
leia(a)
escreval("Digite o 2º valor:")
leia(b)
escreval("Digite o 3º valor:")
leia(c)
resultado<-(a*a)+(b*b)+(c*c)
escreval ("O valor da soma do quadrado desses 3 valores é de:",resultado)



Fimalgoritmo