Algoritmo "L01AB"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   :  Solicita os graus em fahrenheit e converte para celsius
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
celsius:real
fahrenheit:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("Digite a temperatura em fahrenheit:")
Leia (fahrenheit)
celsius<-(fahrenheit-32)*(5/9)
Escreval ("A temperatura em celsius é de:", celsius, "º")


Fimalgoritmo