Algoritmo "L01C"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Calcula o volume de uma late
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
volume:real
raio:real
altura:Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("Digite o raio² da lata:")
Leia (raio)
Escreva ("Digite a altura da lata:")
Leia (altura)
volume<-PI*raio^2*altura
Escreva ("O volume da lata é de:",volume)



Fimalgoritmo
