Algoritmo "L01F"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   :  Solicita dois valores e faz a troca entre eles
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
a:caractere
b:caractere
c:caractere


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("Digite o valor de a:")
leia(a)
Escreval ("Digite o valor de b:")
leia(b)
c<-a
a<-b
b<-c
Escreval ("O valor de a é:",a)
Escreval ("O valor de b é:",b)


Fimalgoritmo