Algoritmo "L01G"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicita 4 numero e faz a soma e multiplicação de cada um deles
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
numero1:inteiro
numero2:inteiro
numero3:inteiro
numero4:inteiro



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval ("Digite o 1º número:")
leia(numero1)
escreval ("Digite o 2º número:")
leia(numero2)
escreval ("Digite o 3º número:")
leia(numero3)
escreval ("Digite o 4º número:")
leia(numero4)

escreval("A soma do 1º com o 2º é de:",numero1+numero2)
escreval("A soma do 1º com o 3º é de:",numero1+numero3)
escreval("A soma do 1º com o 4º é de:",numero1+numero4)
escreval("A soma do 2º com o 3º é de:",numero2+numero3)
escreval("A soma do 2º com o 4º é de:",numero2+numero4)
escreval("A soma do 3º com o 4º é de:",numero3+numero4)
escreval("A multiplicação do 1º com o 2º é de:",numero1*numero2)
escreval("A multiplicação do 1º com o 3º é de:",numero1*numero3)
escreval("A multiplicação do 1º com o 4º é de:",numero1*numero4)
escreval("A multiplicação do 2º com o 3º é de:",numero2*numero3)
escreval("A multiplicação do 2º com o 4º é de:",numero2*numero4)
escreval("A multiplicação do 3º com o 4º é de:",numero3*numero4)





Fimalgoritmo