Algoritmo "L01H"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   :  Calcula o volume de uma caixa retangular
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis
volume:real
comprimento:real
altura:real
largura:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o comprimento da caixa:")
leia(comprimento)
escreva("Digite a altura da caixa:")
leia(altura)
escreva("Digite a largura da caixa:")
leia(largura)
volume<-comprimento*altura*largura
escreva("O volume da caixa retângular é de:",volume)


Fimalgoritmo