Algoritmo "L01I"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicita dois valores e exibe o quadrado da diferença do valor
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis
numero1:inteiro
numero2:inteiro
resultado:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Digite o 1º número:")
leia (numero1)
escreva ("Digite o 2º número:")
leia (numero2)
resultado<-(numero1-numero2)^2
escreva ("O quadrado da diferença do valor é de:", resultado)


Fimalgoritmo