Algoritmo "Ex A - Pag46 Manzano"
// Disciplina  : Lógica de programação
// Professor   : Jailson
// Descrição   : Tabuada de multiplicar de 1 até 10.
// Autor(a)    : Alanis Ribeiro
// Data atual  : 31/03/2023
Var
   // Seção de Declarações das variáveis
   numero, contadornumero2, resultado:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite um número e receba sua tabuada:")
   leia (numero)

   enquanto (contadornumero2<10) faca

      contadornumero2<-contadornumero2+1

      resultado<-contadornumero2*numero

      escreval(numero," x",contadornumero2," =",resultado)

   fimenquanto


Fimalgoritmo
