Algoritmo "Ex E - Pag 46 Manzano"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresentar os resultados das potências de 3, variando do expoente 0 até o expoente 15. Deve ser considerado  que  qualquer  número  elevado  a  zero  é  1,  e  elevado  a  1  é  ele  próprio.  Observe  que neste exercício não pode ser utilizado o operador de exponenciação do portuguol (^).
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
contador:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

enquanto contador<=15 faca
escreval ("3 elevado à", contador, "=", 3^contador)


contador<-contador+1
fimenquanto


Fimalgoritmo