Algoritmo "Ex I - Pag 46 Manzano"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Exibe a média aritmética
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
contador:inteiro
numero:real
soma:real
media:real



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

enquanto contador<10 faca
escreval ("Digite um número:")
leia (numero)
soma<-soma+numero
contador<-contador+1
fimenquanto

media<-soma/10
escreval ("Soma:", soma)
escreval ("Média aritmética:", media)





Fimalgoritmo