Algoritmo "Ex A - Pag 50 Manzano"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200.
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
numero:inteiro
resultado:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
numero<-15
repita
resultado<-numero*numero
escreval (resultado)
numero<-numero+1
ate numero>200


Fimalgoritmo
