Algoritmo "Ex C - Pag 50 Manzano"
// Disciplina  : Lógica de programação
// Professor   : Jailson
// Descrição   :  Números divisíveis por 4 entre 1 e 200
// Autor(a)    : Alanis Ribeiro
// Data atual  : 03/04/2023
Var
// Seção de Declarações das variáveis
contador:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
repita
se (contador mod 4 = 0) entao
escreval(contador)
fimse
contador<-contador+1
ate (contador=200)

Fimalgoritmo
