Algoritmo "Ex 33 - Número iguais"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   :  Solicita dois valores e diz se são iguais
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
valor1:inteiro
valor2:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Digite o 1º número")
leia(valor1)
escreval ("Digite o 2º número")
leia(valor2)
se valor1=valor2 entao
escreval ("Número iguais")
fimse


Fimalgoritmo