Algoritmo "Exercicio14 - Maior que dez ou não"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Solicitar um valor e verificar se é maior que 10
// Autor(a)    : Obama
// Data atual  : 24/03/2023
Var
   // Seção de Declarações das variáveis
   numero:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite um valor :")
   Leia(numero)
   se (numero>10) entao
      Escreval("Valor digitado é maior que 10")
   senao
      Escreval("Valor digitado não é maior que 10")
   fimse
Fimalgoritmo