Algoritmo "Exercicio27"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicita um valor e diz se ele é positivo, negativo ou zero
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
   // Seção de Declarações das variáveis
   valor:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite um valor :")
   Leia(valor)
   se(valor<0) entao
      escreval("O valor digitado é Negativo")
   senao
     se(valor=0) entao
        escreval("O valor digitado é 0")
      senao
        escreval("O valor digitado é positivo")
      fimse
   fimse

Fimalgoritmo







Fimalgoritmo