Algoritmo "38 - Senha e usuário"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   :  Solicita codigo e a senhra para você ter o acesso permitido
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
codigo:inteiro
senha:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o seu código")
leia(codigo)
se (codigo<>1234) entao
escreval ("Usuário inválido")
senao
escreval ("Digite sua senha:")
leia(senha)
se senha<>9999 entao
escreval ("Senha incorreta")
senao
escreval ("Acesso permitido")
fimse
fimse



Fimalgoritmo
