Algoritmo "ExemploEscolhaCaso"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicita um número e exibe o dia correspondente a esse número
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
   // Seção de Declarações das variáveis
   valor:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite um valor :")
   Leia(valor)
   Escolha valor

   caso 1
      escreval("Domingo")
   caso 2
      escreval("Segunda-Feira")
   caso 3
      escreval("Terça-Feira")
   caso 4
      escreval("Quarta-Feira")
   caso 5
      escreval("Quinta-Feira")
   caso 6
      escreval("Sexta-Feira")
   caso 7
      escreval("Sábado")
   outrocaso
      escreval("Não há dia correspondente")
   fimescolha

Fimalgoritmo