Algoritmo "Exercico 15"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicita um valor e diz se ele é negativo ou positivo
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
   // Seção de Declarações das variáveis
   numero:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval ("Digite um valor:")
   leia (numero)
   se (numero>=0)entao
      escreval ("Valor digitado é positivo")
   senao
      escreval ("Valor digitado é negativo")
   fimse


Fimalgoritmo