Algoritmo "Ex 19 - Valor maior"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicita dois valores e diz qual é o maior
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
valor1:real
valor2:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Digite o 1º valor:")
leia(valor1)
escreval ("Digite o 2º valor:")
leia(valor2)
se valor1>valor2 entao
escreval (valor1," é maior que", valor2)
senão
escreval (valor2," é maior que", valor1)

fimse


Fimalgoritmo