Algoritmo "Ex 20 - Ordem crescente"
// Disciplina   : [Linguagem de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   :  Solicita dois valores e ordena em ordem crescente
// Autor(a)    : Alanis Ribeiro
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
numero1:inteiro
numero2:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Digite o 1º número:")
leia(numero1)
escreva ("Digite o 2º número:")
leia(numero2)
se (numero1<numero2) entao
escreva ("Ordem crescente:",numero1,numero2)
senão
escreva ("Ordem crescente:",numero2,numero1)

fimse


Fimalgoritmo